
create schema banquinho;


use	banquinho;


create table if not exists clientes(
cliente_id INT PRIMARY KEY,
cliente_nome VARCHAR(50) NOT NULL,
cliente_rua VARCHAR(100) NOT NULL,
cliente_numero INT,
cliente_bairro VARCHAR(50) NOT NULL,
cliente_cidade VARCHAR(50) NOT NULL,
cliente_uf CHAR(2) NOT NULL
);


CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR(100) NOT NULL,
FUNC_CARGO VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(100) NOT NULL,
PRO_PRECO DECIMAL(5,2) NOT NULL,
PROD_QTDE INT NOT NULL);

CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_NUMERO INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_VAL_TOTAL DECIMAL(10,2)NOT NULL,
CLIENTE INT NOT NULL,
FUNCIONARIO INT NOT NULL,

CONSTRAINT FK_CLIENTE FOREIGN KEY(CLIENTE)
REFERENCES CLIENTES(CLIENTE_ID),


CONSTRAINT FK_FUNCIONARIOS FOREIGN KEY(FUNCIONARIO)
REFERENCES  FUNCIONARIOS(FUNC_ID)
);
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PEDIDO INT,
PRODUTO INT,
PRIMARY KEY(PEDIDO, PRODUTO),
CONSTRAINT FK_PRODUTO FOREIGN KEY(PEDIDO)
REFERENCES PEDIDOS(PED_NUMERO),
CONSTRAINT FK_PRODUTO FOREIGN KEY(PRODUTO)